make sure all vignettes generated locally not on CRAN
From Brian Ripley:

This has added Suggests: rstan but does not use it conditionally, so on an M1 Mac

Packages suggested but not available for checking:
   'brms', 'rstan', 'rstanarm', 'rstantools'
...
--- re-building ‘large-data.Rmd’ using rmarkdown
Quitting from lines 45-48 (large-data.Rmd)
Error: processing vignette 'large-data.Rmd' failed with diagnostics:
there is no package called 'rstan'

This is because rstan requires package V8 hence v8, probably the hardest of all external software to install and no one has yet succeeded in porting to arm64.